#stack.yml
version: '3.1'

services:
    db:
        image: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        ports:
            - "3306:3306"
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
    node-app:
        build: app
        image: node-app
        environment:
            - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
        ports:
            - '8085:8085'
        depends_on:
            - mongodb
        volumes:
            - .:/
        networks:
            - node-network

    mongodb:
        image: mongo:6-jammy
        ports:
            - '27017:27017'
        volumes:
            - dbdata6:/data/db
        networks:
            - node-network

volumes:
    dbdata6:

networks:
    node-network:
        driver: bridge
